Web/Areas/Admin/Controllers/CertificationController.cs
using AutoMapper;
using Business.Interfaces;
using DTO.DTOs.CertificationDtos;
using Entities.Concrete;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class CertificationController : Controller
    {
        private readonly IGenericService<Certification> _certificationGenericService;
        private readonly IMapper _mapper;

        public CertificationController(IGenericService<Certification> certificationGenericService, IMapper mapper)
        {
            _certificationGenericService = certificationGenericService;
            _mapper = mapper;
        }
        public IActionResult Index()
        {
            TempData["active"] = "sertifika";
            return View(_mapper.Map<List<CertificationListDto>>(_certificationGenericService.GetAll()));
        }
        public IActionResult Delete(int id)
        {
            TempData["active"] = "sertifika";
            var deletedEntity = _certificationGenericService.GetById(id);
            _certificationGenericService.Delete(deletedEntity);
            TempData["message"] = "Silme işlemi başarılı";
            return RedirectToAction("Index");
        }
        public IActionResult Add()
        {
            TempData["active"] = "sertifika";
            return View(new CertificationAddDto());
        }
        [HttpPost]
        public IActionResult Add(CertificationAddDto dto)
        {
            TempData["active"] = "sertifika";
            if (ModelState.IsValid)
            {
                _certificationGenericService.Insert(_mapper.Map<Certification>(dto));
                TempData["message"] = "Sertifika ekleme işlemi başarılı";
                return RedirectToAction("Index");
            }
            return View(dto);
        }
        public IActionResult Update(int id)
        {
            TempData["active"] = "sertifika";
            return View(_mapper.Map<CertificationUpdateDto>(_certificationGenericService.GetById(id)));
        }
        [HttpPost]
        public IActionResult Update(CertificationUpdateDto model)
        {
            TempData["active"] = "sertifika";
            if (ModelState.IsValid)
            {
                var updatedCertification = _certificationGenericService.GetById(model.Id);
                updatedCertification.Description = model.Description;
                _certificationGenericService.Update(updatedCertification);
                TempData["message"] = "Güncelleme işlemi başarılı.";
                return RedirectToAction("Index");
            }
            return View(model);
        }
    }
}

Web/Areas/Admin/Views/Certification/Add.cshtml
@model CertificationAddDto
@{
    Layout = "_Layout";
}
<form asp-action="Add" asp-controller="Certification" method="post">
    <div class="form-group mb-3">
        <label>Sertifika Bilgisi: </label><span asp-validation-for="@Model.Description" class="text-danger"></span>
        <input asp-for="@Model.Description" class="form-control" />
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-outline-primary">Kaydet</button>
    </div>
</form>

Web/Areas/Admin/Views/Certification/Index.cshtml
@model List<CertificationListDto>
@{
    Layout = "_Layout";
}
<div class="text-right mb-2">
    <a asp-action="Add" asp-controller="Certification" class="btn btn-outline-dark">Yeni Kayıt</a>
</div>
<table class="table table-hover table-striped table-bordered table-sm">
    <thead>
        <tr>
            <th>Sertifika Bilgisi</th>
            <th>İşlem</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Description</td>
                <td>
                    <a asp-action="Update" asp-controller="Certification" asp-route-id="@item.Id" class="btn btn-warning btn-sm mr-2">Güncelle</a>
                    <a onclick="return confirm('Silmek istediğinizden eminmisiniz?')" asp-action="Delete" asp-controller="Certification" asp-route-id="@item.Id" class="btn btn-danger btn-sm mr-2">Sil</a>
                </td>
            </tr>
        }
    </tbody>

</table>

Web/Areas/Admin/Views/Certification/Update.cshtml
@model CertificationUpdateDto
@{
    Layout = "_Layout";
}
<form asp-action="Update" asp-controller="Certification" method="post">
    <input type="hidden" asp-for="Id" />
    <div class="form-group mb-3">
        <label>Sertifika Bilgisi: </label><span asp-validation-for="@Model.Description" class="text-danger"></span>
        <input asp-for="@Model.Description" class="form-control" />
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-outline-primary">Kaydet</button>
    </div>
</form>