Web/Areas/Admin/Controllers/EducationController.cs
using AutoMapper;
using DataAccess.Interfaces;
using DTO.DTOs.EducationDtos;
using Entities.Concrete;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Web.Areas.Admin.Controllers
{
    public class EducationController : Controller
    {
        private readonly IGenericRepository<Education> _educationGenericService;
        private readonly IMapper _mapper;
        public EducationController(IGenericRepository<Education> educationGenericService, IMapper mapper)
        {
            _educationGenericService = educationGenericService;
            _mapper = mapper;
        }
        [Area("Admin")]
        [Authorize]
        public IActionResult Index()
        {
            TempData["active"] = "egitim";
            return View(_mapper.Map<List<EducationListDto>>(_educationGenericService.GetAll()));
        }
        public IActionResult Delete(int id)
        {
            TempData["active"] = "egitim";
            var deletedEntity = _educationGenericService.GetById(id);
            _educationGenericService.Delete(deletedEntity);
            TempData["message"] = "Silme işlemi başarılı";
            return RedirectToAction("Index");
        }
        public IActionResult Add()
        {
            TempData["active"] = "egitim";
            return View(new EducationAddDto());
        }
        [HttpPost]
        public IActionResult Add(EducationAddDto model)
        {
            TempData["active"] = "egitim";
            if (ModelState.IsValid)
            {
                _educationGenericService.Insert(_mapper.Map<Education>(model));
                TempData["message"] = "Ekleme işlemi başarılı";
                return RedirectToAction("Index");
            }
            return View(model);
        }
        public IActionResult Update(int id)
        {
            TempData["active"] = "egitim";
            return View(_mapper.Map<Education>(_educationGenericService.GetById(id)));
        }
        [HttpPost]
        public IActionResult Update(EducationUpdateDto model)
        {
            if (ModelState.IsValid)
            {
                var data = _educationGenericService.GetById(model.Id);
                data.StartDate = model.StartDate;
                data.EndDate = model.EndDate;
                data.Title = model.Title;
                data.SubTitle = model.SubTitle;
                data.Description = model.Description;
                _educationGenericService.Update(data);
                TempData["message"] = "Güncelleme işlemi başarılı";
                return RedirectToAction("Index");
            }
            return View(model);
        }
    }
}

Web/Areas/Admin/Controllers/InterestController.cs
using AutoMapper;
using Business.Interfaces;
using DTO.DTOs.InterestDtos;
using Entities.Concrete;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class InterestController : Controller
    {
        private readonly IGenericService<Interest> _genericService;
        private readonly IMapper _mapper;

        public InterestController(IGenericService<Interest> genericService, IMapper mapper)
        {
            _genericService = genericService;
            _mapper = mapper;
        }
        public IActionResult Index()
        {
            TempData["active"] = "hobi";
            return View(_mapper.Map<InterestListDto>(_genericService.GetAll()));
        }
        public IActionResult Add()
        {
            TempData["active"] = "hobi";
            return View(new InterestAddDto());
        }
        [HttpPost]
        public IActionResult Add(InterestAddDto model)
        {
            TempData["active"] = "hobi";
            if (ModelState.IsValid)
            {
                _genericService.Insert(_mapper.Map<Interest>(model));
                TempData["message"] = "Ekleme işleminiz başarılı";
                return RedirectToAction("Index");
            }
            return View(model);
        }
        public IActionResult Delete(int id)
        {
            TempData["active"] = "hobi";
            var deletedEntity = _genericService.GetById(id);
            _genericService.Delete(deletedEntity);
            TempData["message"] = "Silme işlemi başarılı";
            return RedirectToAction("Index");
        }
        public IActionResult Update(int id)
        {
            TempData["active"] = "sertifika";
            return View(_mapper.Map<InterestUpdateDto>(_genericService.GetById(id)));
        }
        [HttpPost]
        public IActionResult Update(InterestUpdateDto model)
        {
            TempData["active"] = "hobi";
            if (ModelState.IsValid)
            {
                var data = _genericService.GetById(model.Id);
                data.Description = model.Description;
                _genericService.Update(data);
                TempData["message"] = "Güncelleme işlemi başarılı.";
                return RedirectToAction("Index");
            }
            return View(model);
        }
    }
}

Web/Areas/Admin/Controllers/SkillController.cs
using AutoMapper;
using Business.Interfaces;
using DTO.DTOs.SkillDtos;
using Entities.Concrete;
using Microsoft.AspNetCore.Mvc;

namespace Web.Areas.Admin.Controllers
{
    public class SkillController:Controller
    {
        private readonly IMapper _mapper;
        private readonly IGenericService<Skill> _genericService;
        public SkillController(IGenericService<Skill> genericService,IMapper mapper)
        {
            _genericService = genericService;
            _mapper = mapper;
        }
        
            
        
        public IActionResult Index()
        {
            TempData["active"] = "yetenek";
            return View(_mapper.Map<SkillListDto>(_genericService.GetAll()));
        }
        public IActionResult Add()
        {
            TempData["active"] = "yetenek";
            return View(new SkillAddDto());
        }
        [HttpPost]
        public IActionResult Add(SkillAddDto model)
        {
            TempData["active"] = "yetenek";
            if (ModelState.IsValid)
            {
                _genericService.Insert(_mapper.Map<Skill>(model));
                TempData["message"] = "Ekleme işleminiz başarılı";
                return RedirectToAction("Index");
            }
            return View(model);
        }
        public IActionResult Delete(int id)
        {
            TempData["active"] = "hobi";
            var deletedEntity = _genericService.GetById(id);
            _genericService.Delete(deletedEntity);
            TempData["message"] = "Silme işlemi başarılı";
            return RedirectToAction("Index");
        }
        public IActionResult Update(int id)
        {
            TempData["active"] = "yetenek";
            return View(_mapper.Map<SkillUpdateDto>(_genericService.GetById(id)));
        }
        [HttpPost]
        public IActionResult Update(SkillUpdateDto model)
        {
            TempData["active"] = "yetenek";
            if (ModelState.IsValid)
            {
                var data = _genericService.GetById(model.Id);
                data.Description = model.Description;
                _genericService.Update(data);
                TempData["message"] = "Güncelleme işlemi başarılı.";
                return RedirectToAction("Index");
            }
            return View(model);
        }
    }
}

Web/Controllers/AuthController.cs
using Business.Interfaces;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using Web.Models;

namespace Web.Controllers
{

    public class AuthController : Controller
    {
        private readonly IAppUserService _appUserService;

        public AuthController(IAppUserService appUserService)
        {
            _appUserService = appUserService;
        }
        [HttpGet]
        public IActionResult Login()
        {
            return View(new AppUserLoginModel());
        }
        [HttpPost]
        public async Task<IActionResult> Login(AppUserLoginModel model)
        {
            if (ModelState.IsValid)
            {
                if (_appUserService.CheckUser(model.UserName, model.Password))
                {
                    var claims = new List<Claim>
                    {
                        new Claim(ClaimTypes.Name,model.UserName),
                        new Claim(ClaimTypes.Role,"Admin")
                    };
                    var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                    var authProperties = new AuthenticationProperties
                    {
                        IsPersistent = model.RememberMe
                    };
                    await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimsIdentity), authProperties);
                    return RedirectToAction("Index", "Home", new { @area = "Admin" });
                }
                ModelState.AddModelError("", "Kullanıcı adı veya şifre hatalı");
            }
            return View(model);
        }
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Index", "Home", new
            {
                @area = ""
            });
        }
    }
}

Web/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="tr">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Simple Sidebar - Start Bootstrap Template</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="~/css/simple-sidebar.css" rel="stylesheet" />
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
</head>
<body>
    <div class="d-flex" id="wrapper">
        <!-- Sidebar-->
        <div class="border-end bg-white" id="sidebar-wrapper">
            <div class="sidebar-heading border-bottom bg-light">CvApp Admin Panel</div>
            <div class="list-group list-group-flush">
                <a asp-action="Index" asp-controller="Home" asp-area="Admin" class="@(TempData["active"]?.ToString()=="Bilgilerim"?"active":"") list-group-item list-group-item-action list-group-item-light p-3">Bilgilerim</a>
                <a asp-action="ChangePassword" asp-controller="Home" asp-area="Admin" class="@(TempData["active"]?.ToString()=="Sifre"?"active":"") list-group-item list-group-item-action list-group-item-light p-3">Şifre Değişikliği</a>
                <a asp-action="Index" asp-controller="Certification" asp-area="Admin" class="@(TempData["active"]?.ToString()=="sertifika"?"active":"") list-group-item list-group-item-action list-group-item-light p-3">Sertifikalarım</a>
                <a asp-action="Index" asp-controller="Education" asp-area="Admin" class="@(TempData["active"]?.ToString()=="egitim"?"active":"") list-group-item list-group-item-action list-group-item-light p-3">Eğitimlerim</a>
                <a asp-action="Index" asp-controller="Experience" asp-area="Admin" class="@(TempData["active"]?.ToString()=="deneyim"?"active":"") list-group-item list-group-item-action list-group-item-light p-3">Deneyimlerim</a>
                <a asp-action="Index" asp-controller="Interest" asp-area="Admin" class="@(TempData["active"]?.ToString()=="hobi"?"active":"") list-group-item list-group-item-action list-group-item-light p-3">Hobilerim</a>
                <a asp-action="Index" asp-controller="Skill" asp-area="Admin" class="@(TempData["active"]?.ToString()=="yetenek"?"active":"") list-group-item list-group-item-action list-group-item-light p-3">Yeteneklerim</a>
                <a asp-action="Index" asp-controller="SocialMediaIcon" asp-area="Admin" class="@(TempData["active"]?.ToString()=="ikon"?"active":"") list-group-item list-group-item-action list-group-item-light p-3">Sosyal Medya</a>
                <a asp-action="Logout" asp-area="" asp-controller="Auth" class="list-group-item list-group-item-action list-group-item-light p-3">Çıkış Yap</a>
            </div>
        </div>
        <!-- Page content wrapper-->
        <div id="page-content-wrapper">
            <!-- Top navigation-->
            <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
                <div class="container-fluid">
                    <button class="btn btn-outline-primary" id="sidebarToggle">Menü</button>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                    @*<div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav ms-auto mt-2 mt-lg-0">
                            <li class="nav-item active"><a class="nav-link" href="#!">Home</a></li>
                            <li class="nav-item"><a class="nav-link" href="#!">Link</a></li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>
                                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="#!">Action</a>
                                    <a class="dropdown-item" href="#!">Another action</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" href="#!">Something else here</a>
                                </div>
                            </li>
                        </ul>
                    </div>*@
                </div>
            </nav>
            <!-- Page content-->
            <div class="container-fluid">
                @{ if (!string.IsNullOrWhiteSpace(TempData["message"]?.ToString()))
                    {
                        <div class="alert alert-info alert-dismissible fade show my-2" role="alert">
                            @TempData["message"].ToString()
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span area-hidden="true">&times;</span>
                            </button>
                        </div>
                    }
                }               

                @RenderBody()
            </div>
        </div>

    </div>
    <!-- Bootstrap core JS-->
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
</body>
</html>